### ISSUE TITLE
Give me Ideas

### ISSUE THREAD

**Issue by CalebQ42** [CalebQ42/LinuxPA#10]
Please suggest ideas!

**Comment by RoyiAvital** [comment]
Have a look here - https://discourse.appimage.org/t/linuxpa-linux-portable-apps-launcher/184.

**Comment by probonopd** [comment]
Hi @CalebQ42 please check out [libappimage](https://github.com/AppImage/AppImageKit) and [libappimageupdate](https://github.com/AppImage/AppImageUpdate), and https://github.com/AppImage/appimaged/issues/5

**Comment by CalebQ42** [comment]
Closed as I've opened up discussions https://github.com/CalebQ42/LinuxPA/discussions
