### ISSUE TITLE
libappimage.so - cannot open shared object file - no such file or directory

### ISSUE THREAD

**Issue by Vortexadecimal** [CalebQ42/LinuxPA#11]
When I run the most recent LinuxPA appimage, I am presented with the following error:

./LinuxPA: error while loading shared libraries: libappimage.so: cannot open shared object file: No such file or directory.

I went back a few versions and it launches fine, however it then immediately auto-updates to the new version and stops working due to the missing dependency. 

Any assistance in getting it to launch without having to install dependencies would be greatly appreciated! : )

**Comment by CalebQ42** [comment]
Oops, sorry about that, 2.1.3.0 ( https://github.com/CalebQ42/LinuxPA/releases/tag/v2.1.3.0 ) should work and should ask if you want to upgrade, though I'll change what the stable version is to 2.1.3.0 to make sure it doesn't update.

**Comment by IITFA** [comment]
I have this problem with the 2.1.4.1 version. The version you linked to works though.

**Comment by CalebQ42** [comment]
I've finally found time to work on LinuxPA again! The latest version (2.1.5.0) is no longer using `libappimage.so`, but should retain many of the benefits. Many thanks to @probonopd who created [https://github.com/probonopd/go-appimage](https://github.com/probonopd/go-appimage) which I could pull out a piece of and convert into a working (if a bit bloated at the moment) library at [https://github.com/CalebQ42/GoAppImage](https://github.com/CalebQ42/GoAppImage). The only issue right now is that you MUST have `unsquashfs` in $PATH (though I might try to work around this by including, or downloading a "portable" version of it) for advanced AppImage integrations.
