### ISSUE TITLE
Chromium

### ISSUE THREAD

**Issue by CalebQ42** [CalebQ42/LinuxPA#2]
It appears Chromium AppImage doesn't like being launched off a flash drive:
`
(chrome:9102): IBUS-WARNING **: The owner of /mnt/Drivey/PortableApps/LinuxPACom/Home/.config/ibus/bus is not belac!
[9102:9102:0914/020344:ERROR:process_singleton_posix.cc(273)] Failed to create /mnt/Drivey/PortableApps/LinuxPACom/Home/.config/chromium/SingletonLock: Operation not permitted
[9102:9102:0914/020344:ERROR:chrome_browser_main.cc(1694)] Failed to create a ProcessSingleton for your profile directory. This means that running multiple instances would start multiple browser processes rather than opening a new window in the existing process. Aborting now to avoid profile corruption.`

**Comment by probonopd** [comment]
What filesystem do you have on your flash drive and does it support owners?

**Comment by CalebQ42** [comment]
fat32 (I know it's probably part of the problem, but I need to have my flash drive work on both Linux and Windows)

**Comment by probonopd** [comment]
Yes that's likely the problem. You could have a loop-mount ext4 on the fat32.

**Comment by CalebQ42** [comment]
how would I go about doing that?

**Comment by probonopd** [comment]
Something along the lines of http://unix.stackexchange.com/questions/43903/create-file-image-container

**Comment by CalebQ42** [comment]
So what you're talking about is creating a file system image on my flash drive? In general I want to stay away from that since I want my linux apps and my windows apps all in one place.

**Comment by CalebQ42** [comment]
Part of me wants to just format my drive to ext4, but I have several utilities on there for Windows that I use when helping my family with computer problems and I still want them to be accessable without needing to download Ext2Fsd or some other utility.

**Comment by CalebQ42** [comment]
Issue happens when flash drive isn't EXT
