### ISSUE TITLE
Does not launch; /home/belac hardcoded

### ISSUE THREAD

**Issue by probonopd** [CalebQ42/LinuxPA#4]
```
me@host:~$ '/home/me/Downloads/LinuxPA' 
panic: PortableApps folder not found!!

goroutine 5 [running]:
panic(0x705ce0, 0xc820190af0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
main.setup()
	/home/belac/Go/src/github.com/CalebQ42/LinuxPA/setup.go:19 +0xaa8
main.appMain(0x7f0dec8bb000, 0xc820016740)
	/home/belac/Go/src/github.com/CalebQ42/LinuxPA/main.go:35 +0x7a
github.com/nelsam/gxui/drivers/gl.StartDriver.func1()
	/home/belac/Go/src/github.com/nelsam/gxui/drivers/gl/driver.go:57 +0x55
github.com/nelsam/gxui/drivers/gl.(*driver).applicationLoop(0xc820016740)
	/home/belac/Go/src/github.com/nelsam/gxui/drivers/gl/driver.go:108 +0x64
created by github.com/nelsam/gxui/drivers/gl.StartDriver
	/home/belac/Go/src/github.com/nelsam/gxui/drivers/gl/driver.go:58 +0x3a6
```

**Comment by CalebQ42** [comment]
It's not that it's hardcoded, that's just where the files are when I compile and it appears it keep the locations internally, so when it crashes it gives the location of the .go files on my computer. If you were to put a PortableApps folder in your home directory the command should work.

**Comment by probonopd** [comment]
Why doesn't it just create one then? :-)

**Comment by CalebQ42** [comment]
I was going to add back in where it would automatically create the PortableApps folder, but got sidetracked.
If you're getting a black window then it probably isn't detecting any apps in the PortableApps folder

**Comment by probonopd** [comment]
The window stays black if I add an AppImage in the folder.

**Comment by CalebQ42** [comment]
Is the AppImage in a folder in the folder? (Later on I'll add where you can
just put the AppImage in the PortableApps folder. It's in a folder so the
app can find the appicon.png and appinfo.ini if they are present)

**Comment by probonopd** [comment]
Ah, with a folder in a folder it shows the name of the folder in the menu. Shouldn't it use the information from the .desktop file inside the AppImage instead, for determining the name and icon?

**Comment by CalebQ42** [comment]
I can add that later
