### ISSUE TITLE
Only shows black screen

### ISSUE THREAD

**Issue by probonopd** [CalebQ42/LinuxPA#5]
Running on `xubuntu-16.04-desktop-amd64.iso `:

![screenshot_2017-04-03_18-34-47](https://cloud.githubusercontent.com/assets/2480569/24619988/4e920f4a-189c-11e7-9b68-52236ef2957f.png)

**Comment by CalebQ42** [comment]
:/ might be a problem with the gui library as it's working fine on my computer. I'm probably going to start working on switching it over to a library that's a direct binding to gtk.

**Comment by CalebQ42** [comment]
redone gui (didn't take as long as I though). Next time you open LinuxPA up it should automatically update (still need to add updating UI, so it will just take longer to start)

**Comment by probonopd** [comment]
This is how it looks now on `ubuntu-16.04-desktop-amd64.iso`:

![screenshot from 2017-04-05 23-04-39](https://cloud.githubusercontent.com/assets/2480569/24719747/531265d8-1a54-11e7-8e9a-bd5b9fc4a3a9.png)
