### ISSUE TITLE
portable home folders to survive appimage updates

### ISSUE THREAD

**Issue by Kodiman** [CalebQ42/LinuxPA#9]
hi, your LinuxPA is excellent! as a complete solution to make LinuxPA appimage updates easy, please add an environment variable inside LinuxPA for each appimage program to have its own settings folders that survive version updates. an environment variable (such as LPAAPPNAME) that is the short application name (the prefix and/or desktop entry name) of the launched appimage. and, can rename the existing PANAME to such as LPAFILENAME to have both methods clearly available as options. much appreciated. thanks.

common.sh
export HOME=$PWD/Home-PA/$LPAAPPNAME.home
export XDG_CONFIG_HOME=$PWD/Home-PA/$LPAAPPNAME.config
results in the versionless subfolders from app name...
/Home-PA/Firefox.AppImage.home
/Home-PA/Firefox.AppImage.config

common.sh
export HOME=$PWD/Home-PA/$LPAFILENAME.home
export XDG_CONFIG_HOME=$PWD/Home-PA/$LPAFILENAME.config
results in the "versioned" subfolders from file name...
/Home-PA/Firefox-54.0.glibc2.3.4-x86_64.AppImage.home
/Home-PA/Firefox-54.0.glibc2.3.4-x86_64.AppImage.config

**Comment by CalebQ42** [comment]
Next update i'll probably be adding the variable $APPNAME and changing $PANAME to $FILENAME

_Sent from my Google Nexus 5 CAF using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Kodiman** [comment]
yes, that is good. much appreciated. thanks!

**Comment by Kodiman** [comment]
hi. thanks for solving that. you are the best.
